name: build
on: push
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        working-directory: ./my-app
        run: npm install
      - name: Build Project
        working-directory: ./my-app
        run: npm run build
      - name: Run tests
        working-directory: ./my-app
        run: npm test
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist